#!/bin/bash
usage() {
	cat <<-END 2>&1
	vsync USER@HOST FILE
	use rsync to sync FILE to remote USER@HOST
END
	exit
}
if [ $# -ne 2 -o ! -e $2 ]; then
	usage
fi
mkpath=$2
rpath=$(dirname $2)
if [ -f $2 ]; then
	mkpath=$(dirname $2)
fi
rsync -Cau --rsync-path='mkdir -p ~/.veil'"$mkpath"' && rsync' "$2" "$1"':~/.veil'"$rpath"
